module.exports = (sequelize,DataTypes)=>{
    const Man_hrs_and_product_main_table = sequelize.define("Man_hrs_and_product_main_table",{
           
            product_id:{
                type:DataTypes.STRING(20),
                primaryKey:true,
                allowNull:false
            },
            date_from:{
                type:DataTypes.STRING(10),
                primaryKey:true,
                allowNull:false
            },
            date_from:{
                type:DataTypes.STRING(10),
                primaryKey:true,
                allowNull:false
            },
            date_to:{
                type:DataTypes.STRING(10),
                primaryKey:true,
                allowNull:false
            },
            product_name:{
                type:DataTypes.STRING(300)
            },
           
            standard:{
                type:DataTypes.STRING(2)
            },
            batch_size:{
                type:DataTypes.DOUBLE
            },
            batch:{
                type:DataTypes.DOUBLE
            },
            product_group:{
                type:DataTypes.STRING(25)
            },
           
            synthesis_mn_hr:{
                type:DataTypes.DOUBLE
            },
            syn_mn_into_batch:{
                type:DataTypes.DOUBLE
            },
            sec_qc_percen:{
                     type:DataTypes.DOUBLE
            },
            syn_pilot_perc:{
                type:DataTypes.DOUBLE
            },  
            syn_art_perc:{
                type:DataTypes.DOUBLE
            },
            by_busi_perc:{
                type:DataTypes.DOUBLE
            },
            syn_total:{
                type:DataTypes.DOUBLE
            },
            qc_man_hr:{
                type:DataTypes.DOUBLE
            },
            qc_man_into_batch:{
                type:DataTypes.DOUBLE
            },
            qc_sec_perc:{
                type:DataTypes.DOUBLE 
            },
            syn_pilot_qc_perc:{
                type:DataTypes.DOUBLE
            },
            syn_pro_qc_perc:{
                type:DataTypes.DOUBLE
            },
            by_business_qc:{
                type:DataTypes.DOUBLE
            },
            qc_total:{
                type:DataTypes.DOUBLE
            },
            Sales_qty:{
                type:DataTypes.DOUBLE,
            },
            sales_amt:{
                type:DataTypes.DOUBLE,
            },
            sales_product:{
                type:DataTypes.DOUBLE
            },
          sale_by_busins:{
            type:DataTypes.DOUBLE
          },
          sale_total:{
            type:DataTypes.DOUBLE
          },
         prod_amt:{
            type:DataTypes.DOUBLE
         },
         prod_sec:{
            type:DataTypes.DOUBLE
         },
         prod_syn_pilot:{
            type:DataTypes.DOUBLE
         },
         prod_tot:{
            type:DataTypes.DOUBLE
         },
        /* foun_drill_qty:{
            type:DataTypes.DOUBLE
         },
         cost_raw_m_qty:{
            type:DataTypes.DOUBLE
         },*/
         carryovr_qty:{
            type:DataTypes.DOUBLE
         },
         opening_stk_qty:{
            type:DataTypes.DOUBLE
         },
         opening_st_amt:{
            type:DataTypes.DOUBLE
         },
         opening_wip_qty:{
            type:DataTypes.DOUBLE
         },
         opening_wip_fix_amt:{
            type:DataTypes.DOUBLE
         },
         opening_wip_variable_amt:{
            type:DataTypes.DOUBLE
         },
         opening_wip_amt:{
            type:DataTypes.DOUBLE
         },
         product_in:{
            type:DataTypes.DOUBLE
         },
         material_cost:{
            type:DataTypes.DOUBLE
         },
         packing_material:{
            type:DataTypes.DOUBLE
         },
         material_pack_tot:{
            type:DataTypes.DOUBLE
         },
         labor_dir_cost_mn_hr_fix_cost:{
            type:DataTypes.DOUBLE
         },
         labor_dir_cost_mn_hr_var_cost:{
            type:DataTypes.DOUBLE,
         },
         labor_cost_qc_mn_hr_fix_cost:{
            type:DataTypes.DOUBLE
         },
         labor_cost_qc_mn_hr_var_cost:{
            type:DataTypes.DOUBLE,
         },
         labor_cost_qc_mn_hr_fix_cost:{
            type:DataTypes.DOUBLE
         },
         labor_cost_support_dept_fix_cost:{
            type:DataTypes.DOUBLE,
         },
         labor_cost_support_dept_var_cost:{
            type:DataTypes.DOUBLE,
         },
         tot_fix_cost:{
            type:DataTypes.DOUBLE,
         },
         tot_var_cost:{
            type:DataTypes.DOUBLE,
         },
         rndFixedlabor:{
            type:DataTypes.DOUBLE,
         },
        rndlabor_cost_variation:{
            type:DataTypes.DOUBLE,
        },
        business_fixed_costs:{
            type:DataTypes.DOUBLE,
        },
        common_fixed_cost:{
            type:DataTypes.DOUBLE,
        },
        fixed_ratio_sum:{
            type:DataTypes.DOUBLE,
        },
        variable_sum:{
            type:DataTypes.DOUBLE,
        },
        rnd_sum:{
            type:DataTypes.DOUBLE,
        },
        depreciation_by_business_sale:{
            type:DataTypes.DOUBLE,
        },
        depreciation_by_product_direct:{
            type:DataTypes.DOUBLE,
        },
        depreciation_common_by_sale:{
            type:DataTypes.DOUBLE,
        },
        depreciation_sum:{
            type:DataTypes.DOUBLE,
        },
        food_expense:{
            type:DataTypes.DOUBLE,
        },
        common_benefits:{
            type:DataTypes.DOUBLE,
        },
        benefit_tot:{
            type:DataTypes.DOUBLE,
        },
        direct_payment:{
            type:DataTypes.DOUBLE,
        },
        payment_common:{
            type:DataTypes.DOUBLE,
        },
        payment_tot:{
            type:DataTypes.DOUBLE,
        },
        repaire_prod_direct:{
            type:DataTypes.DOUBLE,
        },
        repaire_by_business:{
            type:DataTypes.DOUBLE,
        },
        repaire_common:{
            type:DataTypes.DOUBLE,
        },
        repair_total:{
            type:DataTypes.DOUBLE,
        },
        fuel_dir_cost:{
            type:DataTypes.DOUBLE,
        },
        consumable_dir_prod_cost:{
            type:DataTypes.DOUBLE,
        },
        consumable_by_busins:{
            type:DataTypes.DOUBLE,
        },
        consumable_commn_sale:{
            type:DataTypes.DOUBLE,
        },
        consumable_sum:{
            type:DataTypes.DOUBLE,
        },
        tax_by_sale:{
            type:DataTypes.DOUBLE,
        },
        tax_by_common:{
            type:DataTypes.DOUBLE,
        },
        tax_total:{
            type:DataTypes.DOUBLE,
        },
        insurance_dir_sale:{
            type:DataTypes.DOUBLE,
        },
        insurance_commn_sale:{
            type:DataTypes.DOUBLE,
        },
        insurance_tot:{
            type:DataTypes.DOUBLE,
        },

        education_fee:{
            type:DataTypes.DOUBLE,
        },
        vechicle_maint_cost:{
            type:DataTypes.DOUBLE,
        },
        book_print_fee:{
            type:DataTypes.DOUBLE,
        },
        travel_expense_direct:{
            type:DataTypes.DOUBLE,
        },
        travel_expense_common:{
            type:DataTypes.DOUBLE,
        },
        teavel_expense_tot:{
            type:DataTypes.DOUBLE,
        },
        enteritainment_fee:{
            type:DataTypes.DOUBLE,
        },
        communitaction_cost:{
            type:DataTypes.DOUBLE,
        },

        rent_direct:{
            type:DataTypes.DOUBLE,
        },
        rent_common:{
            type:DataTypes.DOUBLE,
        },
        rent_tot:{
            type:DataTypes.DOUBLE,
        },
        transport_direct:{
            type:DataTypes.DOUBLE,
        },
        transport_common:{
            type:DataTypes.DOUBLE,
        },
        transport_tot:{
            type:DataTypes.DOUBLE,
        },
        overall_tot_fix_cost:{
            type:DataTypes.DOUBLE,
        },
        overall_tot_var_cost:{
            type:DataTypes.DOUBLE,
        },
        overall_total:{
            type:DataTypes.DOUBLE,
        },


        waste_liquid_direct:{
            type:DataTypes.DOUBLE,
        },
        activated_carbon_earth_usage:{
            type:DataTypes.DOUBLE,
        },
        activate_carbon_item_direct:{
            type:DataTypes.DOUBLE,
        },
        common_waste_organic:{
            type:DataTypes.DOUBLE,
        },
        water_waste_plant:{
            type:DataTypes.DOUBLE,
        },
        gelatin_fp:{
            type:DataTypes.DOUBLE,
        },
        general_garbage:{
            type:DataTypes.DOUBLE,
        },
        wastewater_batch:{
            type:DataTypes.DOUBLE,
        },

        wastewater:{
            type:DataTypes.DOUBLE,
        },
        wastewater_perc:{
            type:DataTypes.DOUBLE,
        },
        ww_treat_prod_amt:{
            type:DataTypes.DOUBLE,
        },
        indus_park_basic_fixed_ratio_sum:{
            type:DataTypes.DOUBLE,
        },
        indus_ww_prod_amt:{
            type:DataTypes.DOUBLE,
        },
       
        waste_disposal_var_cost_sum:{
            type:DataTypes.DOUBLE,
        },
        total_fix_var_waste_disposal_cost:{
            type:DataTypes.DOUBLE,
        },
        electric_cost_by_business_fix:{
            type:DataTypes.DOUBLE,
        },


        elec_cost_three_fact_fix:{
            type:DataTypes.DOUBLE,
        },
        elec_power_usage:{
            type:DataTypes.DOUBLE,
        },
        electric_cost_amt:{
            type:DataTypes.DOUBLE,
        },
        elec_cost_amt_per:{
            type:DataTypes.DOUBLE,
        },
        elec_costprod_amt:{
            type:DataTypes.DOUBLE,
        },
        elec_cost_cmmn_var:{
            type:DataTypes.DOUBLE,
        },
        elec_cost_fix_ratio_sum:{
            type:DataTypes.DOUBLE,
        },
        elec_var_cost:{
            type:DataTypes.DOUBLE,
        },

        elec_fix_var_tot_cost:{
            type:DataTypes.DOUBLE,
        },
        pur_wastewatr_batch:{
            type:DataTypes.DOUBLE,
        },
        pur_wastewatr_vol:{
            type:DataTypes.DOUBLE,
        },
        pur_wastewatr_vol_per:{
            type:DataTypes.DOUBLE,
        },
        waste_utility_dir:{
            type:DataTypes.DOUBLE,
        },
        waste_utility_comn_expense:{
            type:DataTypes.DOUBLE,
        },
        water_utility_tot:{
            type:DataTypes.DOUBLE,
        },
        
       


        tot_manu_fix_cost:{
            type:DataTypes.DOUBLE,
        },

        tot_manu_var_cost:{
            type:DataTypes.DOUBLE,
        },
        tot_manu_tot:{
            type:DataTypes.DOUBLE,
        },
        manu_fix_cost:{
            type:DataTypes.DOUBLE,
        },
        manu_var_cost:{
            type:DataTypes.DOUBLE,
        },
        tot_manu_cost:{
            type:DataTypes.DOUBLE,
        },
        dispatch_qty:{
            type:DataTypes.DOUBLE,
        },
        dispatch_cost_sold:{
            type:DataTypes.DOUBLE,
        },
        dispatch_amt:{
            type:DataTypes.DOUBLE,
        },
        

        carry_ovr_stk_qty:{
            type:DataTypes.DOUBLE,
        },

        carry_ovr_stk_amt:{
            type:DataTypes.DOUBLE,
        },
        carry_ovr_mat_fix_cost:{
            type:DataTypes.DOUBLE,
        },
        carry_ovr_mat_var:{
            type:DataTypes.DOUBLE,
        },
        carryovr_mat_tot:{
            type:DataTypes.DOUBLE,
        }
       
        
        
    });
   
    return Man_hrs_and_product_main_table;
}